version: "3.9"

services:
  # Backend Flask
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://admin:admin123@db:5432/dbdit
    networks:
      - dit-network

  # Frontend React (Vite)
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - dit-network

  # PostgreSQL
  db:
    image: postgres:16
    container_name: postgres_server
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: dbdit
    ports:
      - "5432:5432"
    volumes:
      - ditdata:/var/lib/postgresql/data
    networks:
      - dit-network

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - dit-network

# Volume pour PostgreSQL
volumes:
  ditdata:

# Réseau commun
networks:
  dit-network:
    driver: bridge
